{{- $name := "verify-cont-image-signature" }}
{{- include "kyverno-policy.supportedKyvernoCheck" (dict "top" . "ver" ">= 1.6.0-0") }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Checks if the container images are signed with the public keys provided below as k8s secrets
    policies.kyverno.io/description: >-
      This policy verifies the signatures of container images using the public keys that are referenced as secrets. 
      This is in audit mode and hence doesn't block any deployments. But the images that fail the verification will be 
      reported in the policy reports.
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/subject: Pod

spec:
  validationFailureAction: audit
  background: true
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: check-image
      match:
        any:
        - resources:
            kinds:
              - Pod
            namespaces:
              - "*"
      exclude:
        any:
        - resources:
            namespaces:
              - sample-ns
            names:
              - "sample-name"
      verifyImages:
      - imageReferences:
        - "*"
        mutateDigest: true
        attestors:
        - count: 1
          entries:
          - keys:
              publicKeys: |-
                k8s://kyverno/hpe-oci-signing-key-1
          - keys:
              publicKeys: |-
                k8s://kyverno/hpe-oci-signing-key-2
          - keys:
              publicKeys: |-
                k8s://kyverno/hpe-oci-signing-key-3
