apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: cilium-argo-migration
  namespace: {{ .Values.exceptions.namespace }}
spec:
  exceptions:
  - policyName: {{ .Values.exceptions.podSecurity.baseline.policyName }}
    ruleNames:
    - {{ .Values.exceptions.podSecurity.baseline.ruleName }}
  match:
    any:
    - resources:
        kinds:
        - Pod
        namespaces:
        - argo
        names:
        - cilium-live-migration-*-shell-script-*
  podSecurity:
    - controlName: HostPath Volumes
      restrictedField: spec.volumes[*].hostPath
      values:
        - /root/.ssh
