# Note: Ideally this would be two separate exceptions, but
# it doesn't appear that wildcards work in the middle of names,
# so we can't specify something like
#   names:
#   - cray-ims-*-create*
# or
#   names:
#   - cray-ims-*-customize*
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: cray-ims
  namespace: {{ .Values.exceptions.namespace }}
spec:
  exceptions:
  - policyName: {{ .Values.exceptions.podSecurity.baseline.policyName }}
    ruleNames:
    - {{ .Values.exceptions.podSecurity.baseline.ruleName }}
    - autogen-{{ .Values.exceptions.podSecurity.baseline.ruleName }}
  match:
    any:
    - resources:
        kinds:
        - Pod
        - Job
        namespaces:
        - ims
        names:
        - cray-ims*
  podSecurity:
    # cray-ims-*-create*
    - controlName: Capabilities
      images:
        - "*/cray-ims-utils:*"
      restrictedField: spec.initContainers[*].securityContext.capabilities.add
      values:
        - SYS_ADMIN
    - controlName: Privileged Containers
      images:
        - "*/cray-ims-utils:*"
      restrictedField: spec.initContainers[*].securityContext.privileged
      values:
        - "true"

    # cray-ims-*-customize
    - controlName: Capabilities
      images:
        - "*/cray-ims-kiwi-ng-opensuse-x86_64-builder:*"
      restrictedField: spec.initContainers[*].securityContext.capabilities.add
      values:
        - SYS_ADMIN
    - controlName: Capabilities
      images:
        - "*/cray-ims-sshd:*"
      restrictedField: spec.containers[*].securityContext.capabilities.add
      values:
        - SYS_ADMIN
    - controlName: Privileged Containers
      images:
        - "*/cray-ims-kiwi-ng-opensuse-x86_64-builder:*"
      restrictedField: spec.initContainers[*].securityContext.privileged
      values:
        - "true"
    - controlName: Privileged Containers
      images:
        - "*/cray-ims-sshd:*"
      restrictedField: spec.containers[*].securityContext.privileged
      values:
        - "true"
