apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: cray-node-discovery
  namespace: {{ .Values.exceptions.namespace }}
spec:
  exceptions:
  - policyName: {{ .Values.exceptions.podSecurity.baseline.policyName }}
    ruleNames:
    - {{ .Values.exceptions.podSecurity.baseline.ruleName }}
    - autogen-{{ .Values.exceptions.podSecurity.baseline.ruleName }}
  match:
    any:
    - resources:
        kinds:
        - Pod
        - DaemonSet
        namespaces:
        - services
        names:
        - cray-node-discovery*
  podSecurity:
    - controlName: HostPath Volumes
      restrictedField: spec.volumes[*].hostPath
      values:
        - /sys
    - controlName: Host Namespaces
      restrictedField: spec.hostNetwork
      values:
        - "true"
