apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: cray-cps
  namespace: {{ .Values.exceptions.namespace }}
spec:
  exceptions:
  - policyName: {{ .Values.exceptions.podSecurity.baseline.policyName }}
    ruleNames:
    - {{ .Values.exceptions.podSecurity.baseline.ruleName }}
    - autogen-{{ .Values.exceptions.podSecurity.baseline.ruleName }}
  match:
    any:
    - resources:
        kinds:
        - Pod
        - Deployment
        namespaces:
        - services
        names:
        - cray-cps*
  podSecurity:
    - controlName: HostPath Volumes
      restrictedField: spec.volumes[*].hostPath
      values:
        - /etc
        - /var/lib/cps-local
