apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: cray-vault
  namespace: {{ .Values.exceptions.namespace }}
spec:
  exceptions:
  - policyName: {{ .Values.exceptions.podSecurity.baseline.policyName }}
    ruleNames:
    - {{ .Values.exceptions.podSecurity.baseline.ruleName }}
    - autogen-{{ .Values.exceptions.podSecurity.baseline.ruleName }}
  match:
    any:
    - resources:
        kinds:
        - Pod
        - StatefulSet
        namespaces:
        - vault
        names:
        - cray-vault*
  podSecurity:
    - controlName: Capabilities
      images:
        - "*/docker.io/library/vault:*"
      restrictedField: spec.containers[*].securityContext.capabilities.add
      values:
        - IPC_LOCK
        - SETFCAP

    - controlName: Privileged Containers
      images:
        - "*/docker.io/library/ubuntu:*"
      restrictedField: spec.initContainers[*].securityContext.privileged
      values:
        - "true"

    - controlName: Privileged Containers
      images:
        - "*/docker.io/library/ubuntu:*"
      restrictedField: spec.containers[*].securityContext.privileged
      values:
        - "true"
