---
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: istio-initcontainers-exception
  namespace: {{ .Values.exceptions.namespace }}
spec:
  exceptions:
  - policyName: {{ .Values.exceptions.podSecurity.baseline.policyName }}
    ruleNames:
    - {{ .Values.exceptions.podSecurity.baseline.ruleName }}
  match:
    any:
    - resources:
        kinds:
        - Pod
  podSecurity:
  - controlName: Capabilities
    images:
    - '*/istio/proxyv2*'
    restrictedField: spec.initContainers[*].securityContext.capabilities.add
    values:
    - NET_ADMIN
    - NET_RAW
