apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: iuf-argo-media-dir-access
  namespace: {{ .Values.exceptions.namespace }}
spec:
  exceptions:
  - policyName: {{ .Values.exceptions.podSecurity.baseline.policyName }}
    ruleNames:
    - {{ .Values.exceptions.podSecurity.baseline.ruleName }}
  match:
    any:
    - resources:
        kinds:
        - Pod
        names:
        - "*-pre-install-check-*-shell-script-*"
        - "*-deliver-product-*-shell-script-*"
        - "*-deliver-product-*-echo-message-*"
        - "*-deploy-product-*-shell-script-*"
        - "*-deploy-product-*-echo-message-*"
        - "*-update-vcs-config-*-echo-message-*"
        - "*-process-media-*"
        namespaces:
        - argo
  podSecurity:
    - controlName: HostPath Volumes
      restrictedField: spec.volumes[*].hostPath
      values:
        - /etc/cray/upgrade/csm
---
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: iuf-argo-media-sub-dir-access
  namespace: {{ .Values.exceptions.namespace }}
spec:
  exceptions:
  - policyName: {{ .Values.exceptions.podSecurity.baseline.policyName }}
    ruleNames:
    - {{ .Values.exceptions.podSecurity.baseline.ruleName }}
  match:
    any:
    - resources:
        kinds:
        - Pod
        names:
        - "*-deliver-product-*-gitea-upload-content-*"
        - "*-update-cfs-config-*-sat-wrapper-*"
        - "*-prepare-images-*-sat-wrapper-*"
        - "*-deliver-product-*-ims-upload-content-*"
        - "*-deliver-product-*-nexus-docker-load-template-*"
        - "*-deliver-product-*-nexus-helm-load-template-*"
        - "*-deliver-product-*-nexus-rpm-load-template-*"
        - "*-deliver-product-*-nexus-setup-template-*"
        - "*-managed-nodes-rollout-*-sat-wrapper-*"
        namespaces:
        - argo
  podSecurity:
    - controlName: HostPath Volumes
      restrictedField: spec.volumes[*].hostPath
      values:
        - /etc/cray/upgrade/csm/*
---
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: iuf-argo-shell-script
  namespace: {{ .Values.exceptions.namespace }}
spec:
  exceptions:
  - policyName: {{ .Values.exceptions.podSecurity.baseline.policyName }}
    ruleNames:
    - {{ .Values.exceptions.podSecurity.baseline.ruleName }}
  match:
    any:
    - resources:
        kinds:
        - Pod
        names:
        - "*-prepare-images-*-shell-script-*"
        - "*-process-media-*-shell-script-*"
        - "*-pre-install-check-*-shell-script-*"
        - "*-post-install-check-*-shell-script-*"
        - "*-post-install-service-check-*-shell-script-*"
        - "*-deliver-product-*-shell-script-*"
        - "*-deploy-product-*-shell-script-*"
        - "*-management-nodes-rollout-*-shell-script-*"
        - "ncn-lifecycle-rebuild-*-shell-script-*"
        namespaces:
        - argo
  podSecurity:
    - controlName: HostPath Volumes
      restrictedField: spec.volumes[*].hostPath
      values:
        - /root/.ssh
---
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: iuf-argo-ca-certs
  namespace: {{ .Values.exceptions.namespace }}
spec:
  exceptions:
  - policyName: {{ .Values.exceptions.podSecurity.baseline.policyName }}
    ruleNames:
    - {{ .Values.exceptions.podSecurity.baseline.ruleName }}
  match:
    any:
    - resources:
        kinds:
        - Pod
        names:
        - "*-pre-install-check-*-shell-script-*"
        - "*-deliver-product-*-echo-message-*"
        - "*-deliver-product-*-shell-script-*"
        - "*-deploy-product-*-echo-message-*"
        - "*-deploy-product-*-shell-script-*"
        - "*-update-vcs-config-*-echo-message-*"
        - "ncn-lifecycle-rebuild-*"
        namespaces:
        - argo
  podSecurity:
    - controlName: HostPath Volumes
      restrictedField: spec.volumes[*].hostPath
      values:
        - /var/lib/ca-certificates
---
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: iuf-argo-bin-dir
  namespace: {{ .Values.exceptions.namespace }}
spec:
  exceptions:
  - policyName: {{ .Values.exceptions.podSecurity.baseline.policyName }}
    ruleNames:
    - {{ .Values.exceptions.podSecurity.baseline.ruleName }}
  match:
    any:
    - resources:
        kinds:
        - Pod
        names:
        - "ncn-lifecycle-rebuild-*"
        namespaces:
        - argo
  podSecurity:
    - controlName: HostPath Volumes
      restrictedField: spec.volumes[*].hostPath
      values:
        - /usr/bin
