{{- $name := "pod-sec-ctxt-spire-server" }}
{{- if eq (include "kyverno-policy.podSecurityBaseline" (merge (dict "name" $name) .)) "true" }}
{{- include "kyverno-policy.supportedKyvernoCheck" (dict "top" . "ver" ">= 1.6.0-0") }}
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: {{ $name }}
  namespace: spire 
  annotations:
    policies.kyverno.io/title: Disallow Privilege Escalation and Privileged Containers
    policies.kyverno.io/category: Pod Security Standards (Baseline)
    {{- if .Values.podSecuritySeverity }}
    policies.kyverno.io/severity: {{ .Values.podSecuritySeverity }}
    {{- end }}
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Privilege escalation, such as via set-user-ID or set-group-ID file mode, should not be allowed.
      Privileged mode disables most security mechanisms and must not be allowed. This policy ensures the
      `allowPrivilegeEscalation` field is set to `false` and pods do not call for privileged mode.
spec:
  rules:
  - name: set-container-security-context
    match:
      resources:
        kinds:
        - Pod
        selector:
          matchLabels:
            app.kubernetes.io/name: spire-server
    mutate:
      foreach:
      - list: "request.object.spec.containers"
        patchStrategicMerge:
          spec:
            containers:
            - (name): |-
                {{`{{element.name}}`}}
              securityContext:
                allowPrivilegeEscalation: false
                privileged: false
{{- end }}