{{- $name := "pod-sec-ctxt-customer-high-speed" }}
{{- include "kyverno-policy.supportedKyvernoCheck" (dict "top" . "ver" ">= 1.6.0-0") }}
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: {{ $name }}
  namespace: services 
  annotations:
    policies.kyverno.io/title: Require runAsNonRoot, run As Non-Root User, disallow Privilege Escalation and Privileged Containers
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Containers must be required to run as non-root users. Privilege escalation, such as via set-user-ID
      or set-group-ID file mode, should not be allowed. Privileged mode disables most security mechanisms
      and must not be allowed. This policy ensures `runAsNonRoot` is set to `true`, `runAsUser` is either
      unset or set to a number greater than zero, `allowPrivilegeEscalation` field is set to `false` and
      pods do not call for privileged mode.
spec:
  rules:
  - name: set-container-security-context
    match:
      resources:
        kinds:
        - Pod
        selector:
          matchLabels:
            app: customer-high-speed-ingress
    mutate:
      foreach:
      - list: "request.object.spec.containers"
        patchStrategicMerge:
          spec:
            containers:
            - (name): |-
                {{`{{element.name}}`}}
              securityContext:
                +(runAsUser): 2000
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                privileged: false