#These exceptions apply to both prepend-registry and check-image policy
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: check-image-exceptions
  namespace: kyverno
spec:
  exceptions:
  - policyName: prepend-registry
    ruleNames:
    - prepend-registry-containers
    - prepend-registry-initcontainers
  - policyName: check-image
    ruleNames:
    - check-image
  match:
    any:
#diags pods exceptions
    - resources:
        names:
        - '*hms-badger-job-api*'
#uss exceptions
    - resources:
        names:
        - '*slurmctld*'
        - '*slurmdb*'
        - '*pbs*'
        - '*munge*'
        - '*slurm-backup*'
#slingshot pods exceptions
    - resources:
        names:
        - '*slingshot*'
        - '*sshot*'

#old prepend-registry exceptions
    - resources:
        names:
        - '*kea*'
        - '*postgres*'
        - '*nexus*'
    - resources:
        selector:
          matchLabels:
            spilo-role: '*'
    - resources:
        selector:
          matchLabels:
            prepend-registry: disable

