{{- $name := "validate-pod-sec-ctxt-fas" }}
{{- if eq (include "kyverno-policy.podSecurityBaseline" (merge (dict "name" $name) .)) "true" }}
{{- include "kyverno-policy.supportedKyvernoCheck" (dict "top" . "ver" ">= 1.6.0-0") }}
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: {{ $name }}
  namespace: services
  annotations:
    policies.kyverno.io/title: Mutate pod and container security contexts
    policies.kyverno.io/category: Pod Security Standards (Baseline)
    {{- if .Values.podSecuritySeverity }}
    policies.kyverno.io/severity: {{ .Values.podSecuritySeverity }}
    {{- end }}
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Example, highly restrictive mutate policy setting pod and container security context
spec:
  background: true
  validationFailureAction: audit
  rules:
  - name: container-security-context
    match:
      resources:
        kinds:
        - Pod
        selector:
          matchLabels:
            app.kubernetes.io/instance: cray-hms-firmware-action
            app.kubernetes.io/name: cray-fas
    validate:
      message: "Non root security context is not set."
      pattern:
        spec:
          containers:
          - (name): "*"
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              privileged: false
{{- end }}
