---
checkImagePolicy:
  validationFailureAction: Audit
  background: true
  webhookTimeoutSeconds: 30
  failurePolicy: Ignore
  repository: registry.local
  mutateDigest: false
  verifyDigest: false
  imageReferences:
  - "*"
  publicKeys: []
